spring:
  profiles:
    active: local
    
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:mem:testdb;MODE=MySQL;DB_CLOSE_DELAY=1
    driverClassName: org.h2.Driver
    username: sa
    password:
    
logging:
  level:
    root: WARN
    com.openlabs: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} [%4L] - %m%n"

---

spring:
  profiles: local
  
logging:
  level:
    com.openlabs: DEBUG
    
---

spring:
  profiles: dev
  
logging:
  level:
    com.openlabs: DEBUG
---

spring:
  profiles: qa
  
logging:
  level:
    com.openlabs: INFO

---

spring:
  profiles: prod
  
logging:
  level:
    com.openlabs: INFO
    
    