package kr.co.openlabs.examples.model;

import java.io.Serializable;

/**
 * Ac0125 definition.
 * 
 * This file was generated by Ignite Web Console (08/10/2020, 15:05)
 **/
public class Ac0125 implements Serializable {
    /** */
    private static final long serialVersionUID = 0L;

    private String acno;
    
    /** Value for cif. */
    private String cif;

    /** Value for nrfTcd. */
    private String nrfTcd;

    /** Value for tgIvsrYn. */
    private String tgIvsrYn;

    /** Value for rppnTcd. */
    private String rppnTcd;

    /** Value for ntltCtryCod. */
    private String ntltCtryCod;

    /** Value for txnTcd. */
    private String txnTcd;

    /** Value for ntsIcmpnTcd. */
    private String ntsIcmpnTcd;

    /** Value for fntdIpagYnCod. */
    private String fntdIpagYnCod;

    /** Value for acStatTcd. */
    private String acStatTcd;

    /** Value for acPdPcd. */
    private String acPdPcd;

    /** Value for wrpAcYn. */
    private String wrpAcYn;

    /** Value for acPwdErNc. */
    private Long acPwdErNc;

    /** Value for rlnmNrnmTcd. */
    private String rlnmNrnmTcd;

    /** Value for svBkAcPcd. */
    private String svBkAcPcd;

    /** Value for svIvstTcd. */
    private String svIvstTcd;

    /** Value for ivsrCcd. */
    private String ivsrCcd;

    /** Value for keepIttCod. */
    private String keepIttCod;

    /** Value for ksdFndCod. */
    private String ksdFndCod;

    /** Value for acOpnDt. */
    private String acOpnDt;

    /** Value for moviDt. */
    private String moviDt;

    /** Value for acOpnPcd. */
    private String acOpnPcd;

    /** Value for frzAcAplcStaDt. */
    private String frzAcAplcStaDt;

    /** Value for frzAcAplcEndDt. */
    private String frzAcAplcEndDt;

    /** Value for fusbstAcDsgnDt. */
    private String fusbstAcDsgnDt;

    /** Value for fusbstAcAbndDt. */
    private String fusbstAcAbndDt;

    /** Value for elwEducCoptYn. */
    private String elwEducCoptYn;

    /** Value for elwOrdAbleYn. */
    private String elwOrdAbleYn;

    /** Value for etfOrdAbleYn. */
    private String etfOrdAbleYn;

    /** Value for shselUnbAgmtApvYn. */
    private String shselUnbAgmtApvYn;

    /** Value for buyUnbTcd. */
    private String buyUnbTcd;

    /** Value for fuopStplApvYn. */
    private String fuopStplApvYn;

    /** Value for fuopRskNtcYn. */
    private String fuopRskNtcYn;

    /** Value for xempOrdAcYn. */
    private String xempOrdAcYn;

    /** Value for ordNactTcd. */
    private String ordNactTcd;

    /** Value for nmcoCod. */
    private String nmcoCod;

    /** Value for maNlevyDlTcd. */
    private String maNlevyDlTcd;

    /** Value for maNlevyPrcTcd. */
    private String maNlevyPrcTcd;

    /** Value for maLevyNlevyTcd. */
    private String maLevyNlevyTcd;

    /** Value for etfLvrgMaLevyYn. */
    private String etfLvrgMaLevyYn;

    /** Value for ordRstrItemTcd. */
    private String ordRstrItemTcd;

    /** Value for acmtBrCod. */
    private String acmtBrCod;

    /** Value for mtempNo. */
    private String mtempNo;

    /** Value for ivstCnvsEpNo. */
    private String ivstCnvsEpNo;

    /** Value for tustItemCod. */
    private String tustItemCod;

    /** Value for cmaAcYn. */
    private String cmaAcYn;

    /** Value for arsJoinYn. */
    private String arsJoinYn;

    /** Value for htsJoinYn. */
    private String htsJoinYn;

    /** Value for htsShselAbleYn. */
    private String htsShselAbleYn;

    /** Value for pcsJoinYn. */
    private String pcsJoinYn;

    /** Value for pdaJoinYn. */
    private String pdaJoinYn;

    /** Value for sphnJoinYn. */
    private String sphnJoinYn;

    /** Value for crdStplApvYn. */
    private String crdStplApvYn;

    /** Value for apstJoinYn. */
    private String apstJoinYn;

    /** Value for whldEtrsYn. */
    private String whldEtrsYn;

    /** Value for rskAcMaYn. */
    private String rskAcMaYn;

    /** Value for corpRpBuyAbleYn. */
    private String corpRpBuyAbleYn;

    /** Value for corpRpBuyPrcDt. */
    private String corpRpBuyPrcDt;

    /** Value for bcpnOpBuyCvntYn. */
    private String bcpnOpBuyCvntYn;

    /** Value for sbstAcno. */
    private String sbstAcno;

    /** Value for trtxTxnFtxTcd. */
    private String trtxTxnFtxTcd;

    /** Value for orgnTcd. */
    private String orgnTcd;

    /** Value for corpAcTcd. */
    private String corpAcTcd;

    /** Value for crdAcBnsTcd. */
    private String crdAcBnsTcd;

    /** Value for crdAcTcd. */
    private String crdAcTcd;

    /** Value for konxBaseDpaExmtRqsTcd. */
    private String konxBaseDpaExmtRqsTcd;

    /** Value for fornRepIvsrAcTcd. */
    private String fornRepIvsrAcTcd;

    /** Value for fornUqno. */
    private String fornUqno;

    /** Value for fornIvstTcd. */
    private String fornIvstTcd;

    /** Value for bcpnYn. */
    private String bcpnYn;

    /** Value for unrlDlerYn. */
    private String unrlDlerYn;

    /** Value for stDfStlNmigrAcYn. */
    private String stDfStlNmigrAcYn;

    /** Value for ivstInclTcd. */
    private String ivstInclTcd;

    /** Value for elwRskCfmsDmndYn. */
    private String elwRskCfmsDmndYn;

    /** Value for etfRskCfmsDmndYn. */
    private String etfRskCfmsDmndYn;

    /** Value for ivstCnslCoNtrsAcYn. */
    private String ivstCnslCoNtrsAcYn;

    /** Value for persCrinfPrvdAgrmYn. */
    private String persCrinfPrvdAgrmYn;

    /** Value for rtmBnsClrPmsId. */
    private String rtmBnsClrPmsId;

    /** Value for rtmBalPmsId. */
    private String rtmBalPmsId;

    /** Value for crdClsnRflcPmsId. */
    private String crdClsnRflcPmsId;

    /** Value for wkerId. */
    private String wkerId;

    /** Value for wrkTmnlId. */
    private String wrkTmnlId;

    /** Value for wrkDlDttm. */
    private String wrkDlDttm;

    /** Value for guid. */
    private String guid;

    /** Value for fepDrtOrdYn. */
    private String fepDrtOrdYn;

    /** Value for kotcRqsYn. */
    private String kotcRqsYn;

    /** Value for etnOrdAbleYn. */
    private String etnOrdAbleYn;

    /** Value for konxCtrtTcd. */
    private String konxCtrtTcd;

    /** Value for acDtlTcd. */
    private String acDtlTcd;

    /** Value for vlatEtnAbleYn. */
    private String vlatEtnAbleYn;

    /** Value for etfWhldEtrsYn. */
    private String etfWhldEtrsYn;

    /** Value for stkStlLtDt. */
    private String stkStlLtDt;

    /** Empty constructor. **/
    public Ac0125() {
        // No-op.
    }

    /** Full constructor. **/
    public Ac0125(String acno, String cif,
        String nrfTcd,
        String tgIvsrYn,
        String rppnTcd,
        String ntltCtryCod,
        String txnTcd,
        String ntsIcmpnTcd,
        String fntdIpagYnCod,
        String acStatTcd,
        String acPdPcd,
        String wrpAcYn,
        Long acPwdErNc,
        String rlnmNrnmTcd,
        String svBkAcPcd,
        String svIvstTcd,
        String ivsrCcd,
        String keepIttCod,
        String ksdFndCod,
        String acOpnDt,
        String moviDt,
        String acOpnPcd,
        String frzAcAplcStaDt,
        String frzAcAplcEndDt,
        String fusbstAcDsgnDt,
        String fusbstAcAbndDt,
        String elwEducCoptYn,
        String elwOrdAbleYn,
        String etfOrdAbleYn,
        String shselUnbAgmtApvYn,
        String buyUnbTcd,
        String fuopStplApvYn,
        String fuopRskNtcYn,
        String xempOrdAcYn,
        String ordNactTcd,
        String nmcoCod,
        String maNlevyDlTcd,
        String maNlevyPrcTcd,
        String maLevyNlevyTcd,
        String etfLvrgMaLevyYn,
        String ordRstrItemTcd,
        String acmtBrCod,
        String mtempNo,
        String ivstCnvsEpNo,
        String tustItemCod,
        String cmaAcYn,
        String arsJoinYn,
        String htsJoinYn,
        String htsShselAbleYn,
        String pcsJoinYn,
        String pdaJoinYn,
        String sphnJoinYn,
        String crdStplApvYn,
        String apstJoinYn,
        String whldEtrsYn,
        String rskAcMaYn,
        String corpRpBuyAbleYn,
        String corpRpBuyPrcDt,
        String bcpnOpBuyCvntYn,
        String sbstAcno,
        String trtxTxnFtxTcd,
        String orgnTcd,
        String corpAcTcd,
        String crdAcBnsTcd,
        String crdAcTcd,
        String konxBaseDpaExmtRqsTcd,
        String fornRepIvsrAcTcd,
        String fornUqno,
        String fornIvstTcd,
        String bcpnYn,
        String unrlDlerYn,
        String stDfStlNmigrAcYn,
        String ivstInclTcd,
        String elwRskCfmsDmndYn,
        String etfRskCfmsDmndYn,
        String ivstCnslCoNtrsAcYn,
        String persCrinfPrvdAgrmYn,
        String rtmBnsClrPmsId,
        String rtmBalPmsId,
        String crdClsnRflcPmsId,
        String wkerId,
        String wrkTmnlId,
        String wrkDlDttm,
        String guid,
        String fepDrtOrdYn,
        String kotcRqsYn,
        String etnOrdAbleYn,
        String konxCtrtTcd,
        String acDtlTcd,
        String vlatEtnAbleYn,
        String etfWhldEtrsYn,
        String stkStlLtDt) {
        this.cif = cif;
        this.nrfTcd = nrfTcd;
        this.tgIvsrYn = tgIvsrYn;
        this.rppnTcd = rppnTcd;
        this.ntltCtryCod = ntltCtryCod;
        this.txnTcd = txnTcd;
        this.ntsIcmpnTcd = ntsIcmpnTcd;
        this.fntdIpagYnCod = fntdIpagYnCod;
        this.acStatTcd = acStatTcd;
        this.acPdPcd = acPdPcd;
        this.wrpAcYn = wrpAcYn;
        this.acPwdErNc = acPwdErNc;
        this.rlnmNrnmTcd = rlnmNrnmTcd;
        this.svBkAcPcd = svBkAcPcd;
        this.svIvstTcd = svIvstTcd;
        this.ivsrCcd = ivsrCcd;
        this.keepIttCod = keepIttCod;
        this.ksdFndCod = ksdFndCod;
        this.acOpnDt = acOpnDt;
        this.moviDt = moviDt;
        this.acOpnPcd = acOpnPcd;
        this.frzAcAplcStaDt = frzAcAplcStaDt;
        this.frzAcAplcEndDt = frzAcAplcEndDt;
        this.fusbstAcDsgnDt = fusbstAcDsgnDt;
        this.fusbstAcAbndDt = fusbstAcAbndDt;
        this.elwEducCoptYn = elwEducCoptYn;
        this.elwOrdAbleYn = elwOrdAbleYn;
        this.etfOrdAbleYn = etfOrdAbleYn;
        this.shselUnbAgmtApvYn = shselUnbAgmtApvYn;
        this.buyUnbTcd = buyUnbTcd;
        this.fuopStplApvYn = fuopStplApvYn;
        this.fuopRskNtcYn = fuopRskNtcYn;
        this.xempOrdAcYn = xempOrdAcYn;
        this.ordNactTcd = ordNactTcd;
        this.nmcoCod = nmcoCod;
        this.maNlevyDlTcd = maNlevyDlTcd;
        this.maNlevyPrcTcd = maNlevyPrcTcd;
        this.maLevyNlevyTcd = maLevyNlevyTcd;
        this.etfLvrgMaLevyYn = etfLvrgMaLevyYn;
        this.ordRstrItemTcd = ordRstrItemTcd;
        this.acmtBrCod = acmtBrCod;
        this.mtempNo = mtempNo;
        this.ivstCnvsEpNo = ivstCnvsEpNo;
        this.tustItemCod = tustItemCod;
        this.cmaAcYn = cmaAcYn;
        this.arsJoinYn = arsJoinYn;
        this.htsJoinYn = htsJoinYn;
        this.htsShselAbleYn = htsShselAbleYn;
        this.pcsJoinYn = pcsJoinYn;
        this.pdaJoinYn = pdaJoinYn;
        this.sphnJoinYn = sphnJoinYn;
        this.crdStplApvYn = crdStplApvYn;
        this.apstJoinYn = apstJoinYn;
        this.whldEtrsYn = whldEtrsYn;
        this.rskAcMaYn = rskAcMaYn;
        this.corpRpBuyAbleYn = corpRpBuyAbleYn;
        this.corpRpBuyPrcDt = corpRpBuyPrcDt;
        this.bcpnOpBuyCvntYn = bcpnOpBuyCvntYn;
        this.sbstAcno = sbstAcno;
        this.trtxTxnFtxTcd = trtxTxnFtxTcd;
        this.orgnTcd = orgnTcd;
        this.corpAcTcd = corpAcTcd;
        this.crdAcBnsTcd = crdAcBnsTcd;
        this.crdAcTcd = crdAcTcd;
        this.konxBaseDpaExmtRqsTcd = konxBaseDpaExmtRqsTcd;
        this.fornRepIvsrAcTcd = fornRepIvsrAcTcd;
        this.fornUqno = fornUqno;
        this.fornIvstTcd = fornIvstTcd;
        this.bcpnYn = bcpnYn;
        this.unrlDlerYn = unrlDlerYn;
        this.stDfStlNmigrAcYn = stDfStlNmigrAcYn;
        this.ivstInclTcd = ivstInclTcd;
        this.elwRskCfmsDmndYn = elwRskCfmsDmndYn;
        this.etfRskCfmsDmndYn = etfRskCfmsDmndYn;
        this.ivstCnslCoNtrsAcYn = ivstCnslCoNtrsAcYn;
        this.persCrinfPrvdAgrmYn = persCrinfPrvdAgrmYn;
        this.rtmBnsClrPmsId = rtmBnsClrPmsId;
        this.rtmBalPmsId = rtmBalPmsId;
        this.crdClsnRflcPmsId = crdClsnRflcPmsId;
        this.wkerId = wkerId;
        this.wrkTmnlId = wrkTmnlId;
        this.wrkDlDttm = wrkDlDttm;
        this.guid = guid;
        this.fepDrtOrdYn = fepDrtOrdYn;
        this.kotcRqsYn = kotcRqsYn;
        this.etnOrdAbleYn = etnOrdAbleYn;
        this.konxCtrtTcd = konxCtrtTcd;
        this.acDtlTcd = acDtlTcd;
        this.vlatEtnAbleYn = vlatEtnAbleYn;
        this.etfWhldEtrsYn = etfWhldEtrsYn;
        this.stkStlLtDt = stkStlLtDt;
    }

    public String getAcno() {
    	return this.acno;
    }
    
    public void setAcno(String acno) {
    	this.acno = acno;
    }
    
    /**
     * Gets cif
     * 
     * @return Value for cif.
     **/
    public String getCif() {
        return cif;
    }

    /**
     * Sets cif
     * 
     * @param cif New value for cif.
     **/
    public void setCif(String cif) {
        this.cif = cif;
    }

    /**
     * Gets nrfTcd
     * 
     * @return Value for nrfTcd.
     **/
    public String getNrfTcd() {
        return nrfTcd;
    }

    /**
     * Sets nrfTcd
     * 
     * @param nrfTcd New value for nrfTcd.
     **/
    public void setNrfTcd(String nrfTcd) {
        this.nrfTcd = nrfTcd;
    }

    /**
     * Gets tgIvsrYn
     * 
     * @return Value for tgIvsrYn.
     **/
    public String getTgIvsrYn() {
        return tgIvsrYn;
    }

    /**
     * Sets tgIvsrYn
     * 
     * @param tgIvsrYn New value for tgIvsrYn.
     **/
    public void setTgIvsrYn(String tgIvsrYn) {
        this.tgIvsrYn = tgIvsrYn;
    }

    /**
     * Gets rppnTcd
     * 
     * @return Value for rppnTcd.
     **/
    public String getRppnTcd() {
        return rppnTcd;
    }

    /**
     * Sets rppnTcd
     * 
     * @param rppnTcd New value for rppnTcd.
     **/
    public void setRppnTcd(String rppnTcd) {
        this.rppnTcd = rppnTcd;
    }

    /**
     * Gets ntltCtryCod
     * 
     * @return Value for ntltCtryCod.
     **/
    public String getNtltCtryCod() {
        return ntltCtryCod;
    }

    /**
     * Sets ntltCtryCod
     * 
     * @param ntltCtryCod New value for ntltCtryCod.
     **/
    public void setNtltCtryCod(String ntltCtryCod) {
        this.ntltCtryCod = ntltCtryCod;
    }

    /**
     * Gets txnTcd
     * 
     * @return Value for txnTcd.
     **/
    public String getTxnTcd() {
        return txnTcd;
    }

    /**
     * Sets txnTcd
     * 
     * @param txnTcd New value for txnTcd.
     **/
    public void setTxnTcd(String txnTcd) {
        this.txnTcd = txnTcd;
    }

    /**
     * Gets ntsIcmpnTcd
     * 
     * @return Value for ntsIcmpnTcd.
     **/
    public String getNtsIcmpnTcd() {
        return ntsIcmpnTcd;
    }

    /**
     * Sets ntsIcmpnTcd
     * 
     * @param ntsIcmpnTcd New value for ntsIcmpnTcd.
     **/
    public void setNtsIcmpnTcd(String ntsIcmpnTcd) {
        this.ntsIcmpnTcd = ntsIcmpnTcd;
    }

    /**
     * Gets fntdIpagYnCod
     * 
     * @return Value for fntdIpagYnCod.
     **/
    public String getFntdIpagYnCod() {
        return fntdIpagYnCod;
    }

    /**
     * Sets fntdIpagYnCod
     * 
     * @param fntdIpagYnCod New value for fntdIpagYnCod.
     **/
    public void setFntdIpagYnCod(String fntdIpagYnCod) {
        this.fntdIpagYnCod = fntdIpagYnCod;
    }

    /**
     * Gets acStatTcd
     * 
     * @return Value for acStatTcd.
     **/
    public String getAcStatTcd() {
        return acStatTcd;
    }

    /**
     * Sets acStatTcd
     * 
     * @param acStatTcd New value for acStatTcd.
     **/
    public void setAcStatTcd(String acStatTcd) {
        this.acStatTcd = acStatTcd;
    }

    /**
     * Gets acPdPcd
     * 
     * @return Value for acPdPcd.
     **/
    public String getAcPdPcd() {
        return acPdPcd;
    }

    /**
     * Sets acPdPcd
     * 
     * @param acPdPcd New value for acPdPcd.
     **/
    public void setAcPdPcd(String acPdPcd) {
        this.acPdPcd = acPdPcd;
    }

    /**
     * Gets wrpAcYn
     * 
     * @return Value for wrpAcYn.
     **/
    public String getWrpAcYn() {
        return wrpAcYn;
    }

    /**
     * Sets wrpAcYn
     * 
     * @param wrpAcYn New value for wrpAcYn.
     **/
    public void setWrpAcYn(String wrpAcYn) {
        this.wrpAcYn = wrpAcYn;
    }

    /**
     * Gets acPwdErNc
     * 
     * @return Value for acPwdErNc.
     **/
    public Long getAcPwdErNc() {
        return acPwdErNc;
    }

    /**
     * Sets acPwdErNc
     * 
     * @param acPwdErNc New value for acPwdErNc.
     **/
    public void setAcPwdErNc(Long acPwdErNc) {
        this.acPwdErNc = acPwdErNc;
    }

    /**
     * Gets rlnmNrnmTcd
     * 
     * @return Value for rlnmNrnmTcd.
     **/
    public String getRlnmNrnmTcd() {
        return rlnmNrnmTcd;
    }

    /**
     * Sets rlnmNrnmTcd
     * 
     * @param rlnmNrnmTcd New value for rlnmNrnmTcd.
     **/
    public void setRlnmNrnmTcd(String rlnmNrnmTcd) {
        this.rlnmNrnmTcd = rlnmNrnmTcd;
    }

    /**
     * Gets svBkAcPcd
     * 
     * @return Value for svBkAcPcd.
     **/
    public String getSvBkAcPcd() {
        return svBkAcPcd;
    }

    /**
     * Sets svBkAcPcd
     * 
     * @param svBkAcPcd New value for svBkAcPcd.
     **/
    public void setSvBkAcPcd(String svBkAcPcd) {
        this.svBkAcPcd = svBkAcPcd;
    }

    /**
     * Gets svIvstTcd
     * 
     * @return Value for svIvstTcd.
     **/
    public String getSvIvstTcd() {
        return svIvstTcd;
    }

    /**
     * Sets svIvstTcd
     * 
     * @param svIvstTcd New value for svIvstTcd.
     **/
    public void setSvIvstTcd(String svIvstTcd) {
        this.svIvstTcd = svIvstTcd;
    }

    /**
     * Gets ivsrCcd
     * 
     * @return Value for ivsrCcd.
     **/
    public String getIvsrCcd() {
        return ivsrCcd;
    }

    /**
     * Sets ivsrCcd
     * 
     * @param ivsrCcd New value for ivsrCcd.
     **/
    public void setIvsrCcd(String ivsrCcd) {
        this.ivsrCcd = ivsrCcd;
    }

    /**
     * Gets keepIttCod
     * 
     * @return Value for keepIttCod.
     **/
    public String getKeepIttCod() {
        return keepIttCod;
    }

    /**
     * Sets keepIttCod
     * 
     * @param keepIttCod New value for keepIttCod.
     **/
    public void setKeepIttCod(String keepIttCod) {
        this.keepIttCod = keepIttCod;
    }

    /**
     * Gets ksdFndCod
     * 
     * @return Value for ksdFndCod.
     **/
    public String getKsdFndCod() {
        return ksdFndCod;
    }

    /**
     * Sets ksdFndCod
     * 
     * @param ksdFndCod New value for ksdFndCod.
     **/
    public void setKsdFndCod(String ksdFndCod) {
        this.ksdFndCod = ksdFndCod;
    }

    /**
     * Gets acOpnDt
     * 
     * @return Value for acOpnDt.
     **/
    public String getAcOpnDt() {
        return acOpnDt;
    }

    /**
     * Sets acOpnDt
     * 
     * @param acOpnDt New value for acOpnDt.
     **/
    public void setAcOpnDt(String acOpnDt) {
        this.acOpnDt = acOpnDt;
    }

    /**
     * Gets moviDt
     * 
     * @return Value for moviDt.
     **/
    public String getMoviDt() {
        return moviDt;
    }

    /**
     * Sets moviDt
     * 
     * @param moviDt New value for moviDt.
     **/
    public void setMoviDt(String moviDt) {
        this.moviDt = moviDt;
    }

    /**
     * Gets acOpnPcd
     * 
     * @return Value for acOpnPcd.
     **/
    public String getAcOpnPcd() {
        return acOpnPcd;
    }

    /**
     * Sets acOpnPcd
     * 
     * @param acOpnPcd New value for acOpnPcd.
     **/
    public void setAcOpnPcd(String acOpnPcd) {
        this.acOpnPcd = acOpnPcd;
    }

    /**
     * Gets frzAcAplcStaDt
     * 
     * @return Value for frzAcAplcStaDt.
     **/
    public String getFrzAcAplcStaDt() {
        return frzAcAplcStaDt;
    }

    /**
     * Sets frzAcAplcStaDt
     * 
     * @param frzAcAplcStaDt New value for frzAcAplcStaDt.
     **/
    public void setFrzAcAplcStaDt(String frzAcAplcStaDt) {
        this.frzAcAplcStaDt = frzAcAplcStaDt;
    }

    /**
     * Gets frzAcAplcEndDt
     * 
     * @return Value for frzAcAplcEndDt.
     **/
    public String getFrzAcAplcEndDt() {
        return frzAcAplcEndDt;
    }

    /**
     * Sets frzAcAplcEndDt
     * 
     * @param frzAcAplcEndDt New value for frzAcAplcEndDt.
     **/
    public void setFrzAcAplcEndDt(String frzAcAplcEndDt) {
        this.frzAcAplcEndDt = frzAcAplcEndDt;
    }

    /**
     * Gets fusbstAcDsgnDt
     * 
     * @return Value for fusbstAcDsgnDt.
     **/
    public String getFusbstAcDsgnDt() {
        return fusbstAcDsgnDt;
    }

    /**
     * Sets fusbstAcDsgnDt
     * 
     * @param fusbstAcDsgnDt New value for fusbstAcDsgnDt.
     **/
    public void setFusbstAcDsgnDt(String fusbstAcDsgnDt) {
        this.fusbstAcDsgnDt = fusbstAcDsgnDt;
    }

    /**
     * Gets fusbstAcAbndDt
     * 
     * @return Value for fusbstAcAbndDt.
     **/
    public String getFusbstAcAbndDt() {
        return fusbstAcAbndDt;
    }

    /**
     * Sets fusbstAcAbndDt
     * 
     * @param fusbstAcAbndDt New value for fusbstAcAbndDt.
     **/
    public void setFusbstAcAbndDt(String fusbstAcAbndDt) {
        this.fusbstAcAbndDt = fusbstAcAbndDt;
    }

    /**
     * Gets elwEducCoptYn
     * 
     * @return Value for elwEducCoptYn.
     **/
    public String getElwEducCoptYn() {
        return elwEducCoptYn;
    }

    /**
     * Sets elwEducCoptYn
     * 
     * @param elwEducCoptYn New value for elwEducCoptYn.
     **/
    public void setElwEducCoptYn(String elwEducCoptYn) {
        this.elwEducCoptYn = elwEducCoptYn;
    }

    /**
     * Gets elwOrdAbleYn
     * 
     * @return Value for elwOrdAbleYn.
     **/
    public String getElwOrdAbleYn() {
        return elwOrdAbleYn;
    }

    /**
     * Sets elwOrdAbleYn
     * 
     * @param elwOrdAbleYn New value for elwOrdAbleYn.
     **/
    public void setElwOrdAbleYn(String elwOrdAbleYn) {
        this.elwOrdAbleYn = elwOrdAbleYn;
    }

    /**
     * Gets etfOrdAbleYn
     * 
     * @return Value for etfOrdAbleYn.
     **/
    public String getEtfOrdAbleYn() {
        return etfOrdAbleYn;
    }

    /**
     * Sets etfOrdAbleYn
     * 
     * @param etfOrdAbleYn New value for etfOrdAbleYn.
     **/
    public void setEtfOrdAbleYn(String etfOrdAbleYn) {
        this.etfOrdAbleYn = etfOrdAbleYn;
    }

    /**
     * Gets shselUnbAgmtApvYn
     * 
     * @return Value for shselUnbAgmtApvYn.
     **/
    public String getShselUnbAgmtApvYn() {
        return shselUnbAgmtApvYn;
    }

    /**
     * Sets shselUnbAgmtApvYn
     * 
     * @param shselUnbAgmtApvYn New value for shselUnbAgmtApvYn.
     **/
    public void setShselUnbAgmtApvYn(String shselUnbAgmtApvYn) {
        this.shselUnbAgmtApvYn = shselUnbAgmtApvYn;
    }

    /**
     * Gets buyUnbTcd
     * 
     * @return Value for buyUnbTcd.
     **/
    public String getBuyUnbTcd() {
        return buyUnbTcd;
    }

    /**
     * Sets buyUnbTcd
     * 
     * @param buyUnbTcd New value for buyUnbTcd.
     **/
    public void setBuyUnbTcd(String buyUnbTcd) {
        this.buyUnbTcd = buyUnbTcd;
    }

    /**
     * Gets fuopStplApvYn
     * 
     * @return Value for fuopStplApvYn.
     **/
    public String getFuopStplApvYn() {
        return fuopStplApvYn;
    }

    /**
     * Sets fuopStplApvYn
     * 
     * @param fuopStplApvYn New value for fuopStplApvYn.
     **/
    public void setFuopStplApvYn(String fuopStplApvYn) {
        this.fuopStplApvYn = fuopStplApvYn;
    }

    /**
     * Gets fuopRskNtcYn
     * 
     * @return Value for fuopRskNtcYn.
     **/
    public String getFuopRskNtcYn() {
        return fuopRskNtcYn;
    }

    /**
     * Sets fuopRskNtcYn
     * 
     * @param fuopRskNtcYn New value for fuopRskNtcYn.
     **/
    public void setFuopRskNtcYn(String fuopRskNtcYn) {
        this.fuopRskNtcYn = fuopRskNtcYn;
    }

    /**
     * Gets xempOrdAcYn
     * 
     * @return Value for xempOrdAcYn.
     **/
    public String getXempOrdAcYn() {
        return xempOrdAcYn;
    }

    /**
     * Sets xempOrdAcYn
     * 
     * @param xempOrdAcYn New value for xempOrdAcYn.
     **/
    public void setXempOrdAcYn(String xempOrdAcYn) {
        this.xempOrdAcYn = xempOrdAcYn;
    }

    /**
     * Gets ordNactTcd
     * 
     * @return Value for ordNactTcd.
     **/
    public String getOrdNactTcd() {
        return ordNactTcd;
    }

    /**
     * Sets ordNactTcd
     * 
     * @param ordNactTcd New value for ordNactTcd.
     **/
    public void setOrdNactTcd(String ordNactTcd) {
        this.ordNactTcd = ordNactTcd;
    }

    /**
     * Gets nmcoCod
     * 
     * @return Value for nmcoCod.
     **/
    public String getNmcoCod() {
        return nmcoCod;
    }

    /**
     * Sets nmcoCod
     * 
     * @param nmcoCod New value for nmcoCod.
     **/
    public void setNmcoCod(String nmcoCod) {
        this.nmcoCod = nmcoCod;
    }

    /**
     * Gets maNlevyDlTcd
     * 
     * @return Value for maNlevyDlTcd.
     **/
    public String getMaNlevyDlTcd() {
        return maNlevyDlTcd;
    }

    /**
     * Sets maNlevyDlTcd
     * 
     * @param maNlevyDlTcd New value for maNlevyDlTcd.
     **/
    public void setMaNlevyDlTcd(String maNlevyDlTcd) {
        this.maNlevyDlTcd = maNlevyDlTcd;
    }

    /**
     * Gets maNlevyPrcTcd
     * 
     * @return Value for maNlevyPrcTcd.
     **/
    public String getMaNlevyPrcTcd() {
        return maNlevyPrcTcd;
    }

    /**
     * Sets maNlevyPrcTcd
     * 
     * @param maNlevyPrcTcd New value for maNlevyPrcTcd.
     **/
    public void setMaNlevyPrcTcd(String maNlevyPrcTcd) {
        this.maNlevyPrcTcd = maNlevyPrcTcd;
    }

    /**
     * Gets maLevyNlevyTcd
     * 
     * @return Value for maLevyNlevyTcd.
     **/
    public String getMaLevyNlevyTcd() {
        return maLevyNlevyTcd;
    }

    /**
     * Sets maLevyNlevyTcd
     * 
     * @param maLevyNlevyTcd New value for maLevyNlevyTcd.
     **/
    public void setMaLevyNlevyTcd(String maLevyNlevyTcd) {
        this.maLevyNlevyTcd = maLevyNlevyTcd;
    }

    /**
     * Gets etfLvrgMaLevyYn
     * 
     * @return Value for etfLvrgMaLevyYn.
     **/
    public String getEtfLvrgMaLevyYn() {
        return etfLvrgMaLevyYn;
    }

    /**
     * Sets etfLvrgMaLevyYn
     * 
     * @param etfLvrgMaLevyYn New value for etfLvrgMaLevyYn.
     **/
    public void setEtfLvrgMaLevyYn(String etfLvrgMaLevyYn) {
        this.etfLvrgMaLevyYn = etfLvrgMaLevyYn;
    }

    /**
     * Gets ordRstrItemTcd
     * 
     * @return Value for ordRstrItemTcd.
     **/
    public String getOrdRstrItemTcd() {
        return ordRstrItemTcd;
    }

    /**
     * Sets ordRstrItemTcd
     * 
     * @param ordRstrItemTcd New value for ordRstrItemTcd.
     **/
    public void setOrdRstrItemTcd(String ordRstrItemTcd) {
        this.ordRstrItemTcd = ordRstrItemTcd;
    }

    /**
     * Gets acmtBrCod
     * 
     * @return Value for acmtBrCod.
     **/
    public String getAcmtBrCod() {
        return acmtBrCod;
    }

    /**
     * Sets acmtBrCod
     * 
     * @param acmtBrCod New value for acmtBrCod.
     **/
    public void setAcmtBrCod(String acmtBrCod) {
        this.acmtBrCod = acmtBrCod;
    }

    /**
     * Gets mtempNo
     * 
     * @return Value for mtempNo.
     **/
    public String getMtempNo() {
        return mtempNo;
    }

    /**
     * Sets mtempNo
     * 
     * @param mtempNo New value for mtempNo.
     **/
    public void setMtempNo(String mtempNo) {
        this.mtempNo = mtempNo;
    }

    /**
     * Gets ivstCnvsEpNo
     * 
     * @return Value for ivstCnvsEpNo.
     **/
    public String getIvstCnvsEpNo() {
        return ivstCnvsEpNo;
    }

    /**
     * Sets ivstCnvsEpNo
     * 
     * @param ivstCnvsEpNo New value for ivstCnvsEpNo.
     **/
    public void setIvstCnvsEpNo(String ivstCnvsEpNo) {
        this.ivstCnvsEpNo = ivstCnvsEpNo;
    }

    /**
     * Gets tustItemCod
     * 
     * @return Value for tustItemCod.
     **/
    public String getTustItemCod() {
        return tustItemCod;
    }

    /**
     * Sets tustItemCod
     * 
     * @param tustItemCod New value for tustItemCod.
     **/
    public void setTustItemCod(String tustItemCod) {
        this.tustItemCod = tustItemCod;
    }

    /**
     * Gets cmaAcYn
     * 
     * @return Value for cmaAcYn.
     **/
    public String getCmaAcYn() {
        return cmaAcYn;
    }

    /**
     * Sets cmaAcYn
     * 
     * @param cmaAcYn New value for cmaAcYn.
     **/
    public void setCmaAcYn(String cmaAcYn) {
        this.cmaAcYn = cmaAcYn;
    }

    /**
     * Gets arsJoinYn
     * 
     * @return Value for arsJoinYn.
     **/
    public String getArsJoinYn() {
        return arsJoinYn;
    }

    /**
     * Sets arsJoinYn
     * 
     * @param arsJoinYn New value for arsJoinYn.
     **/
    public void setArsJoinYn(String arsJoinYn) {
        this.arsJoinYn = arsJoinYn;
    }

    /**
     * Gets htsJoinYn
     * 
     * @return Value for htsJoinYn.
     **/
    public String getHtsJoinYn() {
        return htsJoinYn;
    }

    /**
     * Sets htsJoinYn
     * 
     * @param htsJoinYn New value for htsJoinYn.
     **/
    public void setHtsJoinYn(String htsJoinYn) {
        this.htsJoinYn = htsJoinYn;
    }

    /**
     * Gets htsShselAbleYn
     * 
     * @return Value for htsShselAbleYn.
     **/
    public String getHtsShselAbleYn() {
        return htsShselAbleYn;
    }

    /**
     * Sets htsShselAbleYn
     * 
     * @param htsShselAbleYn New value for htsShselAbleYn.
     **/
    public void setHtsShselAbleYn(String htsShselAbleYn) {
        this.htsShselAbleYn = htsShselAbleYn;
    }

    /**
     * Gets pcsJoinYn
     * 
     * @return Value for pcsJoinYn.
     **/
    public String getPcsJoinYn() {
        return pcsJoinYn;
    }

    /**
     * Sets pcsJoinYn
     * 
     * @param pcsJoinYn New value for pcsJoinYn.
     **/
    public void setPcsJoinYn(String pcsJoinYn) {
        this.pcsJoinYn = pcsJoinYn;
    }

    /**
     * Gets pdaJoinYn
     * 
     * @return Value for pdaJoinYn.
     **/
    public String getPdaJoinYn() {
        return pdaJoinYn;
    }

    /**
     * Sets pdaJoinYn
     * 
     * @param pdaJoinYn New value for pdaJoinYn.
     **/
    public void setPdaJoinYn(String pdaJoinYn) {
        this.pdaJoinYn = pdaJoinYn;
    }

    /**
     * Gets sphnJoinYn
     * 
     * @return Value for sphnJoinYn.
     **/
    public String getSphnJoinYn() {
        return sphnJoinYn;
    }

    /**
     * Sets sphnJoinYn
     * 
     * @param sphnJoinYn New value for sphnJoinYn.
     **/
    public void setSphnJoinYn(String sphnJoinYn) {
        this.sphnJoinYn = sphnJoinYn;
    }

    /**
     * Gets crdStplApvYn
     * 
     * @return Value for crdStplApvYn.
     **/
    public String getCrdStplApvYn() {
        return crdStplApvYn;
    }

    /**
     * Sets crdStplApvYn
     * 
     * @param crdStplApvYn New value for crdStplApvYn.
     **/
    public void setCrdStplApvYn(String crdStplApvYn) {
        this.crdStplApvYn = crdStplApvYn;
    }

    /**
     * Gets apstJoinYn
     * 
     * @return Value for apstJoinYn.
     **/
    public String getApstJoinYn() {
        return apstJoinYn;
    }

    /**
     * Sets apstJoinYn
     * 
     * @param apstJoinYn New value for apstJoinYn.
     **/
    public void setApstJoinYn(String apstJoinYn) {
        this.apstJoinYn = apstJoinYn;
    }

    /**
     * Gets whldEtrsYn
     * 
     * @return Value for whldEtrsYn.
     **/
    public String getWhldEtrsYn() {
        return whldEtrsYn;
    }

    /**
     * Sets whldEtrsYn
     * 
     * @param whldEtrsYn New value for whldEtrsYn.
     **/
    public void setWhldEtrsYn(String whldEtrsYn) {
        this.whldEtrsYn = whldEtrsYn;
    }

    /**
     * Gets rskAcMaYn
     * 
     * @return Value for rskAcMaYn.
     **/
    public String getRskAcMaYn() {
        return rskAcMaYn;
    }

    /**
     * Sets rskAcMaYn
     * 
     * @param rskAcMaYn New value for rskAcMaYn.
     **/
    public void setRskAcMaYn(String rskAcMaYn) {
        this.rskAcMaYn = rskAcMaYn;
    }

    /**
     * Gets corpRpBuyAbleYn
     * 
     * @return Value for corpRpBuyAbleYn.
     **/
    public String getCorpRpBuyAbleYn() {
        return corpRpBuyAbleYn;
    }

    /**
     * Sets corpRpBuyAbleYn
     * 
     * @param corpRpBuyAbleYn New value for corpRpBuyAbleYn.
     **/
    public void setCorpRpBuyAbleYn(String corpRpBuyAbleYn) {
        this.corpRpBuyAbleYn = corpRpBuyAbleYn;
    }

    /**
     * Gets corpRpBuyPrcDt
     * 
     * @return Value for corpRpBuyPrcDt.
     **/
    public String getCorpRpBuyPrcDt() {
        return corpRpBuyPrcDt;
    }

    /**
     * Sets corpRpBuyPrcDt
     * 
     * @param corpRpBuyPrcDt New value for corpRpBuyPrcDt.
     **/
    public void setCorpRpBuyPrcDt(String corpRpBuyPrcDt) {
        this.corpRpBuyPrcDt = corpRpBuyPrcDt;
    }

    /**
     * Gets bcpnOpBuyCvntYn
     * 
     * @return Value for bcpnOpBuyCvntYn.
     **/
    public String getBcpnOpBuyCvntYn() {
        return bcpnOpBuyCvntYn;
    }

    /**
     * Sets bcpnOpBuyCvntYn
     * 
     * @param bcpnOpBuyCvntYn New value for bcpnOpBuyCvntYn.
     **/
    public void setBcpnOpBuyCvntYn(String bcpnOpBuyCvntYn) {
        this.bcpnOpBuyCvntYn = bcpnOpBuyCvntYn;
    }

    /**
     * Gets sbstAcno
     * 
     * @return Value for sbstAcno.
     **/
    public String getSbstAcno() {
        return sbstAcno;
    }

    /**
     * Sets sbstAcno
     * 
     * @param sbstAcno New value for sbstAcno.
     **/
    public void setSbstAcno(String sbstAcno) {
        this.sbstAcno = sbstAcno;
    }

    /**
     * Gets trtxTxnFtxTcd
     * 
     * @return Value for trtxTxnFtxTcd.
     **/
    public String getTrtxTxnFtxTcd() {
        return trtxTxnFtxTcd;
    }

    /**
     * Sets trtxTxnFtxTcd
     * 
     * @param trtxTxnFtxTcd New value for trtxTxnFtxTcd.
     **/
    public void setTrtxTxnFtxTcd(String trtxTxnFtxTcd) {
        this.trtxTxnFtxTcd = trtxTxnFtxTcd;
    }

    /**
     * Gets orgnTcd
     * 
     * @return Value for orgnTcd.
     **/
    public String getOrgnTcd() {
        return orgnTcd;
    }

    /**
     * Sets orgnTcd
     * 
     * @param orgnTcd New value for orgnTcd.
     **/
    public void setOrgnTcd(String orgnTcd) {
        this.orgnTcd = orgnTcd;
    }

    /**
     * Gets corpAcTcd
     * 
     * @return Value for corpAcTcd.
     **/
    public String getCorpAcTcd() {
        return corpAcTcd;
    }

    /**
     * Sets corpAcTcd
     * 
     * @param corpAcTcd New value for corpAcTcd.
     **/
    public void setCorpAcTcd(String corpAcTcd) {
        this.corpAcTcd = corpAcTcd;
    }

    /**
     * Gets crdAcBnsTcd
     * 
     * @return Value for crdAcBnsTcd.
     **/
    public String getCrdAcBnsTcd() {
        return crdAcBnsTcd;
    }

    /**
     * Sets crdAcBnsTcd
     * 
     * @param crdAcBnsTcd New value for crdAcBnsTcd.
     **/
    public void setCrdAcBnsTcd(String crdAcBnsTcd) {
        this.crdAcBnsTcd = crdAcBnsTcd;
    }

    /**
     * Gets crdAcTcd
     * 
     * @return Value for crdAcTcd.
     **/
    public String getCrdAcTcd() {
        return crdAcTcd;
    }

    /**
     * Sets crdAcTcd
     * 
     * @param crdAcTcd New value for crdAcTcd.
     **/
    public void setCrdAcTcd(String crdAcTcd) {
        this.crdAcTcd = crdAcTcd;
    }

    /**
     * Gets konxBaseDpaExmtRqsTcd
     * 
     * @return Value for konxBaseDpaExmtRqsTcd.
     **/
    public String getKonxBaseDpaExmtRqsTcd() {
        return konxBaseDpaExmtRqsTcd;
    }

    /**
     * Sets konxBaseDpaExmtRqsTcd
     * 
     * @param konxBaseDpaExmtRqsTcd New value for konxBaseDpaExmtRqsTcd.
     **/
    public void setKonxBaseDpaExmtRqsTcd(String konxBaseDpaExmtRqsTcd) {
        this.konxBaseDpaExmtRqsTcd = konxBaseDpaExmtRqsTcd;
    }

    /**
     * Gets fornRepIvsrAcTcd
     * 
     * @return Value for fornRepIvsrAcTcd.
     **/
    public String getFornRepIvsrAcTcd() {
        return fornRepIvsrAcTcd;
    }

    /**
     * Sets fornRepIvsrAcTcd
     * 
     * @param fornRepIvsrAcTcd New value for fornRepIvsrAcTcd.
     **/
    public void setFornRepIvsrAcTcd(String fornRepIvsrAcTcd) {
        this.fornRepIvsrAcTcd = fornRepIvsrAcTcd;
    }

    /**
     * Gets fornUqno
     * 
     * @return Value for fornUqno.
     **/
    public String getFornUqno() {
        return fornUqno;
    }

    /**
     * Sets fornUqno
     * 
     * @param fornUqno New value for fornUqno.
     **/
    public void setFornUqno(String fornUqno) {
        this.fornUqno = fornUqno;
    }

    /**
     * Gets fornIvstTcd
     * 
     * @return Value for fornIvstTcd.
     **/
    public String getFornIvstTcd() {
        return fornIvstTcd;
    }

    /**
     * Sets fornIvstTcd
     * 
     * @param fornIvstTcd New value for fornIvstTcd.
     **/
    public void setFornIvstTcd(String fornIvstTcd) {
        this.fornIvstTcd = fornIvstTcd;
    }

    /**
     * Gets bcpnYn
     * 
     * @return Value for bcpnYn.
     **/
    public String getBcpnYn() {
        return bcpnYn;
    }

    /**
     * Sets bcpnYn
     * 
     * @param bcpnYn New value for bcpnYn.
     **/
    public void setBcpnYn(String bcpnYn) {
        this.bcpnYn = bcpnYn;
    }

    /**
     * Gets unrlDlerYn
     * 
     * @return Value for unrlDlerYn.
     **/
    public String getUnrlDlerYn() {
        return unrlDlerYn;
    }

    /**
     * Sets unrlDlerYn
     * 
     * @param unrlDlerYn New value for unrlDlerYn.
     **/
    public void setUnrlDlerYn(String unrlDlerYn) {
        this.unrlDlerYn = unrlDlerYn;
    }

    /**
     * Gets stDfStlNmigrAcYn
     * 
     * @return Value for stDfStlNmigrAcYn.
     **/
    public String getStDfStlNmigrAcYn() {
        return stDfStlNmigrAcYn;
    }

    /**
     * Sets stDfStlNmigrAcYn
     * 
     * @param stDfStlNmigrAcYn New value for stDfStlNmigrAcYn.
     **/
    public void setStDfStlNmigrAcYn(String stDfStlNmigrAcYn) {
        this.stDfStlNmigrAcYn = stDfStlNmigrAcYn;
    }

    /**
     * Gets ivstInclTcd
     * 
     * @return Value for ivstInclTcd.
     **/
    public String getIvstInclTcd() {
        return ivstInclTcd;
    }

    /**
     * Sets ivstInclTcd
     * 
     * @param ivstInclTcd New value for ivstInclTcd.
     **/
    public void setIvstInclTcd(String ivstInclTcd) {
        this.ivstInclTcd = ivstInclTcd;
    }

    /**
     * Gets elwRskCfmsDmndYn
     * 
     * @return Value for elwRskCfmsDmndYn.
     **/
    public String getElwRskCfmsDmndYn() {
        return elwRskCfmsDmndYn;
    }

    /**
     * Sets elwRskCfmsDmndYn
     * 
     * @param elwRskCfmsDmndYn New value for elwRskCfmsDmndYn.
     **/
    public void setElwRskCfmsDmndYn(String elwRskCfmsDmndYn) {
        this.elwRskCfmsDmndYn = elwRskCfmsDmndYn;
    }

    /**
     * Gets etfRskCfmsDmndYn
     * 
     * @return Value for etfRskCfmsDmndYn.
     **/
    public String getEtfRskCfmsDmndYn() {
        return etfRskCfmsDmndYn;
    }

    /**
     * Sets etfRskCfmsDmndYn
     * 
     * @param etfRskCfmsDmndYn New value for etfRskCfmsDmndYn.
     **/
    public void setEtfRskCfmsDmndYn(String etfRskCfmsDmndYn) {
        this.etfRskCfmsDmndYn = etfRskCfmsDmndYn;
    }

    /**
     * Gets ivstCnslCoNtrsAcYn
     * 
     * @return Value for ivstCnslCoNtrsAcYn.
     **/
    public String getIvstCnslCoNtrsAcYn() {
        return ivstCnslCoNtrsAcYn;
    }

    /**
     * Sets ivstCnslCoNtrsAcYn
     * 
     * @param ivstCnslCoNtrsAcYn New value for ivstCnslCoNtrsAcYn.
     **/
    public void setIvstCnslCoNtrsAcYn(String ivstCnslCoNtrsAcYn) {
        this.ivstCnslCoNtrsAcYn = ivstCnslCoNtrsAcYn;
    }

    /**
     * Gets persCrinfPrvdAgrmYn
     * 
     * @return Value for persCrinfPrvdAgrmYn.
     **/
    public String getPersCrinfPrvdAgrmYn() {
        return persCrinfPrvdAgrmYn;
    }

    /**
     * Sets persCrinfPrvdAgrmYn
     * 
     * @param persCrinfPrvdAgrmYn New value for persCrinfPrvdAgrmYn.
     **/
    public void setPersCrinfPrvdAgrmYn(String persCrinfPrvdAgrmYn) {
        this.persCrinfPrvdAgrmYn = persCrinfPrvdAgrmYn;
    }

    /**
     * Gets rtmBnsClrPmsId
     * 
     * @return Value for rtmBnsClrPmsId.
     **/
    public String getRtmBnsClrPmsId() {
        return rtmBnsClrPmsId;
    }

    /**
     * Sets rtmBnsClrPmsId
     * 
     * @param rtmBnsClrPmsId New value for rtmBnsClrPmsId.
     **/
    public void setRtmBnsClrPmsId(String rtmBnsClrPmsId) {
        this.rtmBnsClrPmsId = rtmBnsClrPmsId;
    }

    /**
     * Gets rtmBalPmsId
     * 
     * @return Value for rtmBalPmsId.
     **/
    public String getRtmBalPmsId() {
        return rtmBalPmsId;
    }

    /**
     * Sets rtmBalPmsId
     * 
     * @param rtmBalPmsId New value for rtmBalPmsId.
     **/
    public void setRtmBalPmsId(String rtmBalPmsId) {
        this.rtmBalPmsId = rtmBalPmsId;
    }

    /**
     * Gets crdClsnRflcPmsId
     * 
     * @return Value for crdClsnRflcPmsId.
     **/
    public String getCrdClsnRflcPmsId() {
        return crdClsnRflcPmsId;
    }

    /**
     * Sets crdClsnRflcPmsId
     * 
     * @param crdClsnRflcPmsId New value for crdClsnRflcPmsId.
     **/
    public void setCrdClsnRflcPmsId(String crdClsnRflcPmsId) {
        this.crdClsnRflcPmsId = crdClsnRflcPmsId;
    }

    /**
     * Gets wkerId
     * 
     * @return Value for wkerId.
     **/
    public String getWkerId() {
        return wkerId;
    }

    /**
     * Sets wkerId
     * 
     * @param wkerId New value for wkerId.
     **/
    public void setWkerId(String wkerId) {
        this.wkerId = wkerId;
    }

    /**
     * Gets wrkTmnlId
     * 
     * @return Value for wrkTmnlId.
     **/
    public String getWrkTmnlId() {
        return wrkTmnlId;
    }

    /**
     * Sets wrkTmnlId
     * 
     * @param wrkTmnlId New value for wrkTmnlId.
     **/
    public void setWrkTmnlId(String wrkTmnlId) {
        this.wrkTmnlId = wrkTmnlId;
    }

    /**
     * Gets wrkDlDttm
     * 
     * @return Value for wrkDlDttm.
     **/
    public String getWrkDlDttm() {
        return wrkDlDttm;
    }

    /**
     * Sets wrkDlDttm
     * 
     * @param wrkDlDttm New value for wrkDlDttm.
     **/
    public void setWrkDlDttm(String wrkDlDttm) {
        this.wrkDlDttm = wrkDlDttm;
    }

    /**
     * Gets guid
     * 
     * @return Value for guid.
     **/
    public String getGuid() {
        return guid;
    }

    /**
     * Sets guid
     * 
     * @param guid New value for guid.
     **/
    public void setGuid(String guid) {
        this.guid = guid;
    }

    /**
     * Gets fepDrtOrdYn
     * 
     * @return Value for fepDrtOrdYn.
     **/
    public String getFepDrtOrdYn() {
        return fepDrtOrdYn;
    }

    /**
     * Sets fepDrtOrdYn
     * 
     * @param fepDrtOrdYn New value for fepDrtOrdYn.
     **/
    public void setFepDrtOrdYn(String fepDrtOrdYn) {
        this.fepDrtOrdYn = fepDrtOrdYn;
    }

    /**
     * Gets kotcRqsYn
     * 
     * @return Value for kotcRqsYn.
     **/
    public String getKotcRqsYn() {
        return kotcRqsYn;
    }

    /**
     * Sets kotcRqsYn
     * 
     * @param kotcRqsYn New value for kotcRqsYn.
     **/
    public void setKotcRqsYn(String kotcRqsYn) {
        this.kotcRqsYn = kotcRqsYn;
    }

    /**
     * Gets etnOrdAbleYn
     * 
     * @return Value for etnOrdAbleYn.
     **/
    public String getEtnOrdAbleYn() {
        return etnOrdAbleYn;
    }

    /**
     * Sets etnOrdAbleYn
     * 
     * @param etnOrdAbleYn New value for etnOrdAbleYn.
     **/
    public void setEtnOrdAbleYn(String etnOrdAbleYn) {
        this.etnOrdAbleYn = etnOrdAbleYn;
    }

    /**
     * Gets konxCtrtTcd
     * 
     * @return Value for konxCtrtTcd.
     **/
    public String getKonxCtrtTcd() {
        return konxCtrtTcd;
    }

    /**
     * Sets konxCtrtTcd
     * 
     * @param konxCtrtTcd New value for konxCtrtTcd.
     **/
    public void setKonxCtrtTcd(String konxCtrtTcd) {
        this.konxCtrtTcd = konxCtrtTcd;
    }

    /**
     * Gets acDtlTcd
     * 
     * @return Value for acDtlTcd.
     **/
    public String getAcDtlTcd() {
        return acDtlTcd;
    }

    /**
     * Sets acDtlTcd
     * 
     * @param acDtlTcd New value for acDtlTcd.
     **/
    public void setAcDtlTcd(String acDtlTcd) {
        this.acDtlTcd = acDtlTcd;
    }

    /**
     * Gets vlatEtnAbleYn
     * 
     * @return Value for vlatEtnAbleYn.
     **/
    public String getVlatEtnAbleYn() {
        return vlatEtnAbleYn;
    }

    /**
     * Sets vlatEtnAbleYn
     * 
     * @param vlatEtnAbleYn New value for vlatEtnAbleYn.
     **/
    public void setVlatEtnAbleYn(String vlatEtnAbleYn) {
        this.vlatEtnAbleYn = vlatEtnAbleYn;
    }

    /**
     * Gets etfWhldEtrsYn
     * 
     * @return Value for etfWhldEtrsYn.
     **/
    public String getEtfWhldEtrsYn() {
        return etfWhldEtrsYn;
    }

    /**
     * Sets etfWhldEtrsYn
     * 
     * @param etfWhldEtrsYn New value for etfWhldEtrsYn.
     **/
    public void setEtfWhldEtrsYn(String etfWhldEtrsYn) {
        this.etfWhldEtrsYn = etfWhldEtrsYn;
    }

    /**
     * Gets stkStlLtDt
     * 
     * @return Value for stkStlLtDt.
     **/
    public String getStkStlLtDt() {
        return stkStlLtDt;
    }

    /**
     * Sets stkStlLtDt
     * 
     * @param stkStlLtDt New value for stkStlLtDt.
     **/
    public void setStkStlLtDt(String stkStlLtDt) {
        this.stkStlLtDt = stkStlLtDt;
    }

    /** {@inheritDoc} **/
    @Override public boolean equals(Object o) {
        if (this == o)
            return true;
        
        if (!(o instanceof Ac0125))
            return false;
        
        Ac0125 that = (Ac0125)o;

        if (cif != null ? !cif.equals(that.cif) : that.cif != null)
            return false;
        

        if (nrfTcd != null ? !nrfTcd.equals(that.nrfTcd) : that.nrfTcd != null)
            return false;
        

        if (tgIvsrYn != null ? !tgIvsrYn.equals(that.tgIvsrYn) : that.tgIvsrYn != null)
            return false;
        

        if (rppnTcd != null ? !rppnTcd.equals(that.rppnTcd) : that.rppnTcd != null)
            return false;
        

        if (ntltCtryCod != null ? !ntltCtryCod.equals(that.ntltCtryCod) : that.ntltCtryCod != null)
            return false;
        

        if (txnTcd != null ? !txnTcd.equals(that.txnTcd) : that.txnTcd != null)
            return false;
        

        if (ntsIcmpnTcd != null ? !ntsIcmpnTcd.equals(that.ntsIcmpnTcd) : that.ntsIcmpnTcd != null)
            return false;
        

        if (fntdIpagYnCod != null ? !fntdIpagYnCod.equals(that.fntdIpagYnCod) : that.fntdIpagYnCod != null)
            return false;
        

        if (acStatTcd != null ? !acStatTcd.equals(that.acStatTcd) : that.acStatTcd != null)
            return false;
        

        if (acPdPcd != null ? !acPdPcd.equals(that.acPdPcd) : that.acPdPcd != null)
            return false;
        

        if (wrpAcYn != null ? !wrpAcYn.equals(that.wrpAcYn) : that.wrpAcYn != null)
            return false;
        

        if (acPwdErNc != null ? !acPwdErNc.equals(that.acPwdErNc) : that.acPwdErNc != null)
            return false;
        

        if (rlnmNrnmTcd != null ? !rlnmNrnmTcd.equals(that.rlnmNrnmTcd) : that.rlnmNrnmTcd != null)
            return false;
        

        if (svBkAcPcd != null ? !svBkAcPcd.equals(that.svBkAcPcd) : that.svBkAcPcd != null)
            return false;
        

        if (svIvstTcd != null ? !svIvstTcd.equals(that.svIvstTcd) : that.svIvstTcd != null)
            return false;
        

        if (ivsrCcd != null ? !ivsrCcd.equals(that.ivsrCcd) : that.ivsrCcd != null)
            return false;
        

        if (keepIttCod != null ? !keepIttCod.equals(that.keepIttCod) : that.keepIttCod != null)
            return false;
        

        if (ksdFndCod != null ? !ksdFndCod.equals(that.ksdFndCod) : that.ksdFndCod != null)
            return false;
        

        if (acOpnDt != null ? !acOpnDt.equals(that.acOpnDt) : that.acOpnDt != null)
            return false;
        

        if (moviDt != null ? !moviDt.equals(that.moviDt) : that.moviDt != null)
            return false;
        

        if (acOpnPcd != null ? !acOpnPcd.equals(that.acOpnPcd) : that.acOpnPcd != null)
            return false;
        

        if (frzAcAplcStaDt != null ? !frzAcAplcStaDt.equals(that.frzAcAplcStaDt) : that.frzAcAplcStaDt != null)
            return false;
        

        if (frzAcAplcEndDt != null ? !frzAcAplcEndDt.equals(that.frzAcAplcEndDt) : that.frzAcAplcEndDt != null)
            return false;
        

        if (fusbstAcDsgnDt != null ? !fusbstAcDsgnDt.equals(that.fusbstAcDsgnDt) : that.fusbstAcDsgnDt != null)
            return false;
        

        if (fusbstAcAbndDt != null ? !fusbstAcAbndDt.equals(that.fusbstAcAbndDt) : that.fusbstAcAbndDt != null)
            return false;
        

        if (elwEducCoptYn != null ? !elwEducCoptYn.equals(that.elwEducCoptYn) : that.elwEducCoptYn != null)
            return false;
        

        if (elwOrdAbleYn != null ? !elwOrdAbleYn.equals(that.elwOrdAbleYn) : that.elwOrdAbleYn != null)
            return false;
        

        if (etfOrdAbleYn != null ? !etfOrdAbleYn.equals(that.etfOrdAbleYn) : that.etfOrdAbleYn != null)
            return false;
        

        if (shselUnbAgmtApvYn != null ? !shselUnbAgmtApvYn.equals(that.shselUnbAgmtApvYn) : that.shselUnbAgmtApvYn != null)
            return false;
        

        if (buyUnbTcd != null ? !buyUnbTcd.equals(that.buyUnbTcd) : that.buyUnbTcd != null)
            return false;
        

        if (fuopStplApvYn != null ? !fuopStplApvYn.equals(that.fuopStplApvYn) : that.fuopStplApvYn != null)
            return false;
        

        if (fuopRskNtcYn != null ? !fuopRskNtcYn.equals(that.fuopRskNtcYn) : that.fuopRskNtcYn != null)
            return false;
        

        if (xempOrdAcYn != null ? !xempOrdAcYn.equals(that.xempOrdAcYn) : that.xempOrdAcYn != null)
            return false;
        

        if (ordNactTcd != null ? !ordNactTcd.equals(that.ordNactTcd) : that.ordNactTcd != null)
            return false;
        

        if (nmcoCod != null ? !nmcoCod.equals(that.nmcoCod) : that.nmcoCod != null)
            return false;
        

        if (maNlevyDlTcd != null ? !maNlevyDlTcd.equals(that.maNlevyDlTcd) : that.maNlevyDlTcd != null)
            return false;
        

        if (maNlevyPrcTcd != null ? !maNlevyPrcTcd.equals(that.maNlevyPrcTcd) : that.maNlevyPrcTcd != null)
            return false;
        

        if (maLevyNlevyTcd != null ? !maLevyNlevyTcd.equals(that.maLevyNlevyTcd) : that.maLevyNlevyTcd != null)
            return false;
        

        if (etfLvrgMaLevyYn != null ? !etfLvrgMaLevyYn.equals(that.etfLvrgMaLevyYn) : that.etfLvrgMaLevyYn != null)
            return false;
        

        if (ordRstrItemTcd != null ? !ordRstrItemTcd.equals(that.ordRstrItemTcd) : that.ordRstrItemTcd != null)
            return false;
        

        if (acmtBrCod != null ? !acmtBrCod.equals(that.acmtBrCod) : that.acmtBrCod != null)
            return false;
        

        if (mtempNo != null ? !mtempNo.equals(that.mtempNo) : that.mtempNo != null)
            return false;
        

        if (ivstCnvsEpNo != null ? !ivstCnvsEpNo.equals(that.ivstCnvsEpNo) : that.ivstCnvsEpNo != null)
            return false;
        

        if (tustItemCod != null ? !tustItemCod.equals(that.tustItemCod) : that.tustItemCod != null)
            return false;
        

        if (cmaAcYn != null ? !cmaAcYn.equals(that.cmaAcYn) : that.cmaAcYn != null)
            return false;
        

        if (arsJoinYn != null ? !arsJoinYn.equals(that.arsJoinYn) : that.arsJoinYn != null)
            return false;
        

        if (htsJoinYn != null ? !htsJoinYn.equals(that.htsJoinYn) : that.htsJoinYn != null)
            return false;
        

        if (htsShselAbleYn != null ? !htsShselAbleYn.equals(that.htsShselAbleYn) : that.htsShselAbleYn != null)
            return false;
        

        if (pcsJoinYn != null ? !pcsJoinYn.equals(that.pcsJoinYn) : that.pcsJoinYn != null)
            return false;
        

        if (pdaJoinYn != null ? !pdaJoinYn.equals(that.pdaJoinYn) : that.pdaJoinYn != null)
            return false;
        

        if (sphnJoinYn != null ? !sphnJoinYn.equals(that.sphnJoinYn) : that.sphnJoinYn != null)
            return false;
        

        if (crdStplApvYn != null ? !crdStplApvYn.equals(that.crdStplApvYn) : that.crdStplApvYn != null)
            return false;
        

        if (apstJoinYn != null ? !apstJoinYn.equals(that.apstJoinYn) : that.apstJoinYn != null)
            return false;
        

        if (whldEtrsYn != null ? !whldEtrsYn.equals(that.whldEtrsYn) : that.whldEtrsYn != null)
            return false;
        

        if (rskAcMaYn != null ? !rskAcMaYn.equals(that.rskAcMaYn) : that.rskAcMaYn != null)
            return false;
        

        if (corpRpBuyAbleYn != null ? !corpRpBuyAbleYn.equals(that.corpRpBuyAbleYn) : that.corpRpBuyAbleYn != null)
            return false;
        

        if (corpRpBuyPrcDt != null ? !corpRpBuyPrcDt.equals(that.corpRpBuyPrcDt) : that.corpRpBuyPrcDt != null)
            return false;
        

        if (bcpnOpBuyCvntYn != null ? !bcpnOpBuyCvntYn.equals(that.bcpnOpBuyCvntYn) : that.bcpnOpBuyCvntYn != null)
            return false;
        

        if (sbstAcno != null ? !sbstAcno.equals(that.sbstAcno) : that.sbstAcno != null)
            return false;
        

        if (trtxTxnFtxTcd != null ? !trtxTxnFtxTcd.equals(that.trtxTxnFtxTcd) : that.trtxTxnFtxTcd != null)
            return false;
        

        if (orgnTcd != null ? !orgnTcd.equals(that.orgnTcd) : that.orgnTcd != null)
            return false;
        

        if (corpAcTcd != null ? !corpAcTcd.equals(that.corpAcTcd) : that.corpAcTcd != null)
            return false;
        

        if (crdAcBnsTcd != null ? !crdAcBnsTcd.equals(that.crdAcBnsTcd) : that.crdAcBnsTcd != null)
            return false;
        

        if (crdAcTcd != null ? !crdAcTcd.equals(that.crdAcTcd) : that.crdAcTcd != null)
            return false;
        

        if (konxBaseDpaExmtRqsTcd != null ? !konxBaseDpaExmtRqsTcd.equals(that.konxBaseDpaExmtRqsTcd) : that.konxBaseDpaExmtRqsTcd != null)
            return false;
        

        if (fornRepIvsrAcTcd != null ? !fornRepIvsrAcTcd.equals(that.fornRepIvsrAcTcd) : that.fornRepIvsrAcTcd != null)
            return false;
        

        if (fornUqno != null ? !fornUqno.equals(that.fornUqno) : that.fornUqno != null)
            return false;
        

        if (fornIvstTcd != null ? !fornIvstTcd.equals(that.fornIvstTcd) : that.fornIvstTcd != null)
            return false;
        

        if (bcpnYn != null ? !bcpnYn.equals(that.bcpnYn) : that.bcpnYn != null)
            return false;
        

        if (unrlDlerYn != null ? !unrlDlerYn.equals(that.unrlDlerYn) : that.unrlDlerYn != null)
            return false;
        

        if (stDfStlNmigrAcYn != null ? !stDfStlNmigrAcYn.equals(that.stDfStlNmigrAcYn) : that.stDfStlNmigrAcYn != null)
            return false;
        

        if (ivstInclTcd != null ? !ivstInclTcd.equals(that.ivstInclTcd) : that.ivstInclTcd != null)
            return false;
        

        if (elwRskCfmsDmndYn != null ? !elwRskCfmsDmndYn.equals(that.elwRskCfmsDmndYn) : that.elwRskCfmsDmndYn != null)
            return false;
        

        if (etfRskCfmsDmndYn != null ? !etfRskCfmsDmndYn.equals(that.etfRskCfmsDmndYn) : that.etfRskCfmsDmndYn != null)
            return false;
        

        if (ivstCnslCoNtrsAcYn != null ? !ivstCnslCoNtrsAcYn.equals(that.ivstCnslCoNtrsAcYn) : that.ivstCnslCoNtrsAcYn != null)
            return false;
        

        if (persCrinfPrvdAgrmYn != null ? !persCrinfPrvdAgrmYn.equals(that.persCrinfPrvdAgrmYn) : that.persCrinfPrvdAgrmYn != null)
            return false;
        

        if (rtmBnsClrPmsId != null ? !rtmBnsClrPmsId.equals(that.rtmBnsClrPmsId) : that.rtmBnsClrPmsId != null)
            return false;
        

        if (rtmBalPmsId != null ? !rtmBalPmsId.equals(that.rtmBalPmsId) : that.rtmBalPmsId != null)
            return false;
        

        if (crdClsnRflcPmsId != null ? !crdClsnRflcPmsId.equals(that.crdClsnRflcPmsId) : that.crdClsnRflcPmsId != null)
            return false;
        

        if (wkerId != null ? !wkerId.equals(that.wkerId) : that.wkerId != null)
            return false;
        

        if (wrkTmnlId != null ? !wrkTmnlId.equals(that.wrkTmnlId) : that.wrkTmnlId != null)
            return false;
        

        if (wrkDlDttm != null ? !wrkDlDttm.equals(that.wrkDlDttm) : that.wrkDlDttm != null)
            return false;
        

        if (guid != null ? !guid.equals(that.guid) : that.guid != null)
            return false;
        

        if (fepDrtOrdYn != null ? !fepDrtOrdYn.equals(that.fepDrtOrdYn) : that.fepDrtOrdYn != null)
            return false;
        

        if (kotcRqsYn != null ? !kotcRqsYn.equals(that.kotcRqsYn) : that.kotcRqsYn != null)
            return false;
        

        if (etnOrdAbleYn != null ? !etnOrdAbleYn.equals(that.etnOrdAbleYn) : that.etnOrdAbleYn != null)
            return false;
        

        if (konxCtrtTcd != null ? !konxCtrtTcd.equals(that.konxCtrtTcd) : that.konxCtrtTcd != null)
            return false;
        

        if (acDtlTcd != null ? !acDtlTcd.equals(that.acDtlTcd) : that.acDtlTcd != null)
            return false;
        

        if (vlatEtnAbleYn != null ? !vlatEtnAbleYn.equals(that.vlatEtnAbleYn) : that.vlatEtnAbleYn != null)
            return false;
        

        if (etfWhldEtrsYn != null ? !etfWhldEtrsYn.equals(that.etfWhldEtrsYn) : that.etfWhldEtrsYn != null)
            return false;
        

        if (stkStlLtDt != null ? !stkStlLtDt.equals(that.stkStlLtDt) : that.stkStlLtDt != null)
            return false;
        
        return true;
    }

    /** {@inheritDoc} **/
    @Override public int hashCode() {
        int res = cif != null ? cif.hashCode() : 0;

        res = 31 * res + (nrfTcd != null ? nrfTcd.hashCode() : 0);

        res = 31 * res + (tgIvsrYn != null ? tgIvsrYn.hashCode() : 0);

        res = 31 * res + (rppnTcd != null ? rppnTcd.hashCode() : 0);

        res = 31 * res + (ntltCtryCod != null ? ntltCtryCod.hashCode() : 0);

        res = 31 * res + (txnTcd != null ? txnTcd.hashCode() : 0);

        res = 31 * res + (ntsIcmpnTcd != null ? ntsIcmpnTcd.hashCode() : 0);

        res = 31 * res + (fntdIpagYnCod != null ? fntdIpagYnCod.hashCode() : 0);

        res = 31 * res + (acStatTcd != null ? acStatTcd.hashCode() : 0);

        res = 31 * res + (acPdPcd != null ? acPdPcd.hashCode() : 0);

        res = 31 * res + (wrpAcYn != null ? wrpAcYn.hashCode() : 0);

        res = 31 * res + (acPwdErNc != null ? acPwdErNc.hashCode() : 0);

        res = 31 * res + (rlnmNrnmTcd != null ? rlnmNrnmTcd.hashCode() : 0);

        res = 31 * res + (svBkAcPcd != null ? svBkAcPcd.hashCode() : 0);

        res = 31 * res + (svIvstTcd != null ? svIvstTcd.hashCode() : 0);

        res = 31 * res + (ivsrCcd != null ? ivsrCcd.hashCode() : 0);

        res = 31 * res + (keepIttCod != null ? keepIttCod.hashCode() : 0);

        res = 31 * res + (ksdFndCod != null ? ksdFndCod.hashCode() : 0);

        res = 31 * res + (acOpnDt != null ? acOpnDt.hashCode() : 0);

        res = 31 * res + (moviDt != null ? moviDt.hashCode() : 0);

        res = 31 * res + (acOpnPcd != null ? acOpnPcd.hashCode() : 0);

        res = 31 * res + (frzAcAplcStaDt != null ? frzAcAplcStaDt.hashCode() : 0);

        res = 31 * res + (frzAcAplcEndDt != null ? frzAcAplcEndDt.hashCode() : 0);

        res = 31 * res + (fusbstAcDsgnDt != null ? fusbstAcDsgnDt.hashCode() : 0);

        res = 31 * res + (fusbstAcAbndDt != null ? fusbstAcAbndDt.hashCode() : 0);

        res = 31 * res + (elwEducCoptYn != null ? elwEducCoptYn.hashCode() : 0);

        res = 31 * res + (elwOrdAbleYn != null ? elwOrdAbleYn.hashCode() : 0);

        res = 31 * res + (etfOrdAbleYn != null ? etfOrdAbleYn.hashCode() : 0);

        res = 31 * res + (shselUnbAgmtApvYn != null ? shselUnbAgmtApvYn.hashCode() : 0);

        res = 31 * res + (buyUnbTcd != null ? buyUnbTcd.hashCode() : 0);

        res = 31 * res + (fuopStplApvYn != null ? fuopStplApvYn.hashCode() : 0);

        res = 31 * res + (fuopRskNtcYn != null ? fuopRskNtcYn.hashCode() : 0);

        res = 31 * res + (xempOrdAcYn != null ? xempOrdAcYn.hashCode() : 0);

        res = 31 * res + (ordNactTcd != null ? ordNactTcd.hashCode() : 0);

        res = 31 * res + (nmcoCod != null ? nmcoCod.hashCode() : 0);

        res = 31 * res + (maNlevyDlTcd != null ? maNlevyDlTcd.hashCode() : 0);

        res = 31 * res + (maNlevyPrcTcd != null ? maNlevyPrcTcd.hashCode() : 0);

        res = 31 * res + (maLevyNlevyTcd != null ? maLevyNlevyTcd.hashCode() : 0);

        res = 31 * res + (etfLvrgMaLevyYn != null ? etfLvrgMaLevyYn.hashCode() : 0);

        res = 31 * res + (ordRstrItemTcd != null ? ordRstrItemTcd.hashCode() : 0);

        res = 31 * res + (acmtBrCod != null ? acmtBrCod.hashCode() : 0);

        res = 31 * res + (mtempNo != null ? mtempNo.hashCode() : 0);

        res = 31 * res + (ivstCnvsEpNo != null ? ivstCnvsEpNo.hashCode() : 0);

        res = 31 * res + (tustItemCod != null ? tustItemCod.hashCode() : 0);

        res = 31 * res + (cmaAcYn != null ? cmaAcYn.hashCode() : 0);

        res = 31 * res + (arsJoinYn != null ? arsJoinYn.hashCode() : 0);

        res = 31 * res + (htsJoinYn != null ? htsJoinYn.hashCode() : 0);

        res = 31 * res + (htsShselAbleYn != null ? htsShselAbleYn.hashCode() : 0);

        res = 31 * res + (pcsJoinYn != null ? pcsJoinYn.hashCode() : 0);

        res = 31 * res + (pdaJoinYn != null ? pdaJoinYn.hashCode() : 0);

        res = 31 * res + (sphnJoinYn != null ? sphnJoinYn.hashCode() : 0);

        res = 31 * res + (crdStplApvYn != null ? crdStplApvYn.hashCode() : 0);

        res = 31 * res + (apstJoinYn != null ? apstJoinYn.hashCode() : 0);

        res = 31 * res + (whldEtrsYn != null ? whldEtrsYn.hashCode() : 0);

        res = 31 * res + (rskAcMaYn != null ? rskAcMaYn.hashCode() : 0);

        res = 31 * res + (corpRpBuyAbleYn != null ? corpRpBuyAbleYn.hashCode() : 0);

        res = 31 * res + (corpRpBuyPrcDt != null ? corpRpBuyPrcDt.hashCode() : 0);

        res = 31 * res + (bcpnOpBuyCvntYn != null ? bcpnOpBuyCvntYn.hashCode() : 0);

        res = 31 * res + (sbstAcno != null ? sbstAcno.hashCode() : 0);

        res = 31 * res + (trtxTxnFtxTcd != null ? trtxTxnFtxTcd.hashCode() : 0);

        res = 31 * res + (orgnTcd != null ? orgnTcd.hashCode() : 0);

        res = 31 * res + (corpAcTcd != null ? corpAcTcd.hashCode() : 0);

        res = 31 * res + (crdAcBnsTcd != null ? crdAcBnsTcd.hashCode() : 0);

        res = 31 * res + (crdAcTcd != null ? crdAcTcd.hashCode() : 0);

        res = 31 * res + (konxBaseDpaExmtRqsTcd != null ? konxBaseDpaExmtRqsTcd.hashCode() : 0);

        res = 31 * res + (fornRepIvsrAcTcd != null ? fornRepIvsrAcTcd.hashCode() : 0);

        res = 31 * res + (fornUqno != null ? fornUqno.hashCode() : 0);

        res = 31 * res + (fornIvstTcd != null ? fornIvstTcd.hashCode() : 0);

        res = 31 * res + (bcpnYn != null ? bcpnYn.hashCode() : 0);

        res = 31 * res + (unrlDlerYn != null ? unrlDlerYn.hashCode() : 0);

        res = 31 * res + (stDfStlNmigrAcYn != null ? stDfStlNmigrAcYn.hashCode() : 0);

        res = 31 * res + (ivstInclTcd != null ? ivstInclTcd.hashCode() : 0);

        res = 31 * res + (elwRskCfmsDmndYn != null ? elwRskCfmsDmndYn.hashCode() : 0);

        res = 31 * res + (etfRskCfmsDmndYn != null ? etfRskCfmsDmndYn.hashCode() : 0);

        res = 31 * res + (ivstCnslCoNtrsAcYn != null ? ivstCnslCoNtrsAcYn.hashCode() : 0);

        res = 31 * res + (persCrinfPrvdAgrmYn != null ? persCrinfPrvdAgrmYn.hashCode() : 0);

        res = 31 * res + (rtmBnsClrPmsId != null ? rtmBnsClrPmsId.hashCode() : 0);

        res = 31 * res + (rtmBalPmsId != null ? rtmBalPmsId.hashCode() : 0);

        res = 31 * res + (crdClsnRflcPmsId != null ? crdClsnRflcPmsId.hashCode() : 0);

        res = 31 * res + (wkerId != null ? wkerId.hashCode() : 0);

        res = 31 * res + (wrkTmnlId != null ? wrkTmnlId.hashCode() : 0);

        res = 31 * res + (wrkDlDttm != null ? wrkDlDttm.hashCode() : 0);

        res = 31 * res + (guid != null ? guid.hashCode() : 0);

        res = 31 * res + (fepDrtOrdYn != null ? fepDrtOrdYn.hashCode() : 0);

        res = 31 * res + (kotcRqsYn != null ? kotcRqsYn.hashCode() : 0);

        res = 31 * res + (etnOrdAbleYn != null ? etnOrdAbleYn.hashCode() : 0);

        res = 31 * res + (konxCtrtTcd != null ? konxCtrtTcd.hashCode() : 0);

        res = 31 * res + (acDtlTcd != null ? acDtlTcd.hashCode() : 0);

        res = 31 * res + (vlatEtnAbleYn != null ? vlatEtnAbleYn.hashCode() : 0);

        res = 31 * res + (etfWhldEtrsYn != null ? etfWhldEtrsYn.hashCode() : 0);

        res = 31 * res + (stkStlLtDt != null ? stkStlLtDt.hashCode() : 0);

        return res;
    }

    /** {@inheritDoc} **/
    @Override public String toString() {
        return "Ac0125 [" + 
            "cif=" + cif + ", " + 
            "nrfTcd=" + nrfTcd + ", " + 
            "tgIvsrYn=" + tgIvsrYn + ", " + 
            "rppnTcd=" + rppnTcd + ", " + 
            "ntltCtryCod=" + ntltCtryCod + ", " + 
            "txnTcd=" + txnTcd + ", " + 
            "ntsIcmpnTcd=" + ntsIcmpnTcd + ", " + 
            "fntdIpagYnCod=" + fntdIpagYnCod + ", " + 
            "acStatTcd=" + acStatTcd + ", " + 
            "acPdPcd=" + acPdPcd + ", " + 
            "wrpAcYn=" + wrpAcYn + ", " + 
            "acPwdErNc=" + acPwdErNc + ", " + 
            "rlnmNrnmTcd=" + rlnmNrnmTcd + ", " + 
            "svBkAcPcd=" + svBkAcPcd + ", " + 
            "svIvstTcd=" + svIvstTcd + ", " + 
            "ivsrCcd=" + ivsrCcd + ", " + 
            "keepIttCod=" + keepIttCod + ", " + 
            "ksdFndCod=" + ksdFndCod + ", " + 
            "acOpnDt=" + acOpnDt + ", " + 
            "moviDt=" + moviDt + ", " + 
            "acOpnPcd=" + acOpnPcd + ", " + 
            "frzAcAplcStaDt=" + frzAcAplcStaDt + ", " + 
            "frzAcAplcEndDt=" + frzAcAplcEndDt + ", " + 
            "fusbstAcDsgnDt=" + fusbstAcDsgnDt + ", " + 
            "fusbstAcAbndDt=" + fusbstAcAbndDt + ", " + 
            "elwEducCoptYn=" + elwEducCoptYn + ", " + 
            "elwOrdAbleYn=" + elwOrdAbleYn + ", " + 
            "etfOrdAbleYn=" + etfOrdAbleYn + ", " + 
            "shselUnbAgmtApvYn=" + shselUnbAgmtApvYn + ", " + 
            "buyUnbTcd=" + buyUnbTcd + ", " + 
            "fuopStplApvYn=" + fuopStplApvYn + ", " + 
            "fuopRskNtcYn=" + fuopRskNtcYn + ", " + 
            "xempOrdAcYn=" + xempOrdAcYn + ", " + 
            "ordNactTcd=" + ordNactTcd + ", " + 
            "nmcoCod=" + nmcoCod + ", " + 
            "maNlevyDlTcd=" + maNlevyDlTcd + ", " + 
            "maNlevyPrcTcd=" + maNlevyPrcTcd + ", " + 
            "maLevyNlevyTcd=" + maLevyNlevyTcd + ", " + 
            "etfLvrgMaLevyYn=" + etfLvrgMaLevyYn + ", " + 
            "ordRstrItemTcd=" + ordRstrItemTcd + ", " + 
            "acmtBrCod=" + acmtBrCod + ", " + 
            "mtempNo=" + mtempNo + ", " + 
            "ivstCnvsEpNo=" + ivstCnvsEpNo + ", " + 
            "tustItemCod=" + tustItemCod + ", " + 
            "cmaAcYn=" + cmaAcYn + ", " + 
            "arsJoinYn=" + arsJoinYn + ", " + 
            "htsJoinYn=" + htsJoinYn + ", " + 
            "htsShselAbleYn=" + htsShselAbleYn + ", " + 
            "pcsJoinYn=" + pcsJoinYn + ", " + 
            "pdaJoinYn=" + pdaJoinYn + ", " + 
            "sphnJoinYn=" + sphnJoinYn + ", " + 
            "crdStplApvYn=" + crdStplApvYn + ", " + 
            "apstJoinYn=" + apstJoinYn + ", " + 
            "whldEtrsYn=" + whldEtrsYn + ", " + 
            "rskAcMaYn=" + rskAcMaYn + ", " + 
            "corpRpBuyAbleYn=" + corpRpBuyAbleYn + ", " + 
            "corpRpBuyPrcDt=" + corpRpBuyPrcDt + ", " + 
            "bcpnOpBuyCvntYn=" + bcpnOpBuyCvntYn + ", " + 
            "sbstAcno=" + sbstAcno + ", " + 
            "trtxTxnFtxTcd=" + trtxTxnFtxTcd + ", " + 
            "orgnTcd=" + orgnTcd + ", " + 
            "corpAcTcd=" + corpAcTcd + ", " + 
            "crdAcBnsTcd=" + crdAcBnsTcd + ", " + 
            "crdAcTcd=" + crdAcTcd + ", " + 
            "konxBaseDpaExmtRqsTcd=" + konxBaseDpaExmtRqsTcd + ", " + 
            "fornRepIvsrAcTcd=" + fornRepIvsrAcTcd + ", " + 
            "fornUqno=" + fornUqno + ", " + 
            "fornIvstTcd=" + fornIvstTcd + ", " + 
            "bcpnYn=" + bcpnYn + ", " + 
            "unrlDlerYn=" + unrlDlerYn + ", " + 
            "stDfStlNmigrAcYn=" + stDfStlNmigrAcYn + ", " + 
            "ivstInclTcd=" + ivstInclTcd + ", " + 
            "elwRskCfmsDmndYn=" + elwRskCfmsDmndYn + ", " + 
            "etfRskCfmsDmndYn=" + etfRskCfmsDmndYn + ", " + 
            "ivstCnslCoNtrsAcYn=" + ivstCnslCoNtrsAcYn + ", " + 
            "persCrinfPrvdAgrmYn=" + persCrinfPrvdAgrmYn + ", " + 
            "rtmBnsClrPmsId=" + rtmBnsClrPmsId + ", " + 
            "rtmBalPmsId=" + rtmBalPmsId + ", " + 
            "crdClsnRflcPmsId=" + crdClsnRflcPmsId + ", " + 
            "wkerId=" + wkerId + ", " + 
            "wrkTmnlId=" + wrkTmnlId + ", " + 
            "wrkDlDttm=" + wrkDlDttm + ", " + 
            "guid=" + guid + ", " + 
            "fepDrtOrdYn=" + fepDrtOrdYn + ", " + 
            "kotcRqsYn=" + kotcRqsYn + ", " + 
            "etnOrdAbleYn=" + etnOrdAbleYn + ", " + 
            "konxCtrtTcd=" + konxCtrtTcd + ", " + 
            "acDtlTcd=" + acDtlTcd + ", " + 
            "vlatEtnAbleYn=" + vlatEtnAbleYn + ", " + 
            "etfWhldEtrsYn=" + etfWhldEtrsYn + ", " + 
            "stkStlLtDt=" + stkStlLtDt +
        "]";
    }
}