server:
  port: 8080
  #servlet:
   # context-path: /api
  
spring:
  profiles:
    active: local
  first:
    datasource:
      driver-class-name: com.p6spy.engine.spy.P6SpyDriver
      jdbc-url: jdbc:p6spy:oracle:thin:@192.168.0.102:1521:ORCLCDB
      username: ejpark
      password: dmdwns
      hikari:
        connection-timeout: 30000 #30 sec
        validation-timeout: 10000 #10 sec
        maximum-pool-size: 50
        connection-test-query: SELECT 1 FROM DUAL
  ignite:
    datasource:
      driver-class-name: org.apache.ignite.IgniteJdbcThinDriver
      jdbc-url: jdbc:ignite:thin://192.168.87.100:10800
      
logging:
  level:
    root: WARN
    com.openlabs: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} [%4L] - %m%n"

mybatis:
  mapper-locations: classpath:com/openlabs/sample/**/mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true

ignite:
  mapper-locations: classpath:com/openlabs/sample/**/cache/**/*.xml
  configuration:
    map-underscore-to-camel-case: true

---

spring:
  profiles: local
logging:
  level:
    com.openlabs: DEBUG
    p6spy: DEBUG
    
---

spring:
  profiles: dev
logging:
  level:
    com.openlabs: DEBUG
    p6spy: DEBUG
---

spring:
  profiles: qa
  
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@192.168.0.102:1521:ORCLCDB
    username: ejpark
    password: dmdwns
    
logging:
  level:
    com.openlabs: INFO

---

spring:
  profiles: prod
  
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@192.168.0.102:1521:ORCLCDB
    username: ejpark
    password: dmdwns

logging:
  level:
    com.openlabs: INFO
    
    